$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$bibtex_use = 2;
$out_dir = '.';
$aux_dir = '.';
@default_files = ('QVC_arXiv_v4.tex', 'QVC_TQGL_supplement_v4.tex');
